### ISSUE TITLE
Use newer s3cmd version

### ISSUE THREAD

**Issue by schickling** [wercker/step-s3sync#4]
Please use a newer version (1.1+) of s3cmd for `step-s3sync`. Its needed for options like `--cf-invalidate` to invalidate a cloudfront distribution.

**Comment by philippfrank** [comment]
@schickling Did you get a newer version running somehow?

**Comment by schickling** [comment]
@philippfrank I've ended up writing my own step: https://github.com/schickling/step-s3-website

**Comment by ascendbruce** [comment]
Thanks @schickling for your step. I also wrote one to fit my usage: https://github.com/ascendbruce/step-s3sync

**Comment by hatchan** [comment]
Hi just letting you guys know, we've updated the step to use s3cmd 1.5.1.2. This step now also bundles the s3cmd, so no more apt-get update and install :-)

**Comment by ascendbruce** [comment]
:+1: Cool!
